pins:
  - pin: 34A
    function: Power GND
    type: gnd

info:
  title: AlphaX 8chan
  name: AlphaX 8chan
  board_url: https://rusefi.com/s/8chan
  image:
    file: 8chan-A-B.jpg
  pins:
    - pin: 34A
      x: 303
      y: 181
