name: rusEFI console

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test Compiler
        run: javac -version

      - name: Build console
        working-directory: ./java_console
        run: ant
